# for inputs
tissue_id_path: "data/references/selected_tissue_ids.csv"
covariates_dir: "data/processed/subsampling/100_rand/covariates/"
expression_dir: "data/processed/subsampling/100_rand/normalized_expression/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"

# for outputs
filtered_expression_output_dir: "output/subsampling/100_rand/clusters_expression/"
clusters_dir: "output/subsampling/100_rand/clusters/"
eqtl_output_dir: "output/subsampling/100_rand/control_eqtl/"
pcqtl_output_dir: "output/subsampling/100_rand/pcqtl/"
pc_output_dir: "output/subsampling/100_rand/pcs/"
overlap_output_dir: "output/subsampling/100_rand/overlap/"
annotations_output_dir: "output/subsampling/100_rand/annotations/"

# for clusters
percent_corr_cutoff: .7