# for inputs
tissue_id_path: "data/references/selected_tissue_ids.csv"
covariates_dir: "data/processed/subsampling/300/covariates/"
expression_dir: "data/processed/subsampling/300/normalized_expression/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"

# for outputs
filtered_expression_output_dir: "output/subsampling_constant_clusters/300/clusters_expression/"
clusters_dir: "output/proteincoding_main/clusters/"
eqtl_output_dir: "output/subsampling_constant_clusters/300/control_eqtl/"
pcqtl_output_dir: "output/subsampling_constant_clusters/300/pcqtl/"
pc_output_dir: "output/subsampling_constant_clusters/300/pcs/"
