tissue_id_path: "data/references/test_tissue_ids.csv"
covariates_dir: "data/processed/covariates_tami/"
expression_dir: "data/processed/normalized_expression_tami/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"

filtered_expression_output_dir: "data/processed/proteincoding/clusters_expression/"
clusters_dir: "output/proteincoding/clusters_tami/"
eqtl_output_dir: "output/proteincoding/control_eqtl/"
pcqtl_output_dir: "output/proteincoding/pcqtl/"
pc_output_dir: "output/proteincoding/pcs/"
overlap_output_dir: "output/proteincoding/overlap/"
annotations_output_dir: "output/proteincoding/annotations/"
corr_dir: "output/proteincoding/correlations/"
