tissue_id_path: "data/references/selected_tissue_ids.csv"
covariates_dir: "data/processed/covariates_tami/"
expression_dir: "data/processed/normalized_expression_tami/"
filtered_expression_output_dir: "data/processed/cluster_allgenes_expression/"
clusters_dir: "output/clusters_allgenes_tami/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"
eqtl_output_dir: "output/control_eqtl_allgenes/"
pcqtl_output_dir: "output/pcqtl_allgenes/"
pc_output_dir: "output/pcs_allgenes/"
overlap_output_dir: "output/overlap_allgenes/"
annotations_output_dir: "output/annotations_allgenes/"
