# for inputs
tissue_id_path: "data/references/selected_tissue_ids.csv"
covariates_dir: "data/processed/covariates_peers/"
expression_dir: "data/processed/normalized_expression_proteincoding/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"

# for outputs
filtered_expression_output_dir: "output/proteincoding_corr_0.5/clusters_expression/"
clusters_dir: "output/proteincoding_corr_0.5/clusters/"
eqtl_output_dir: "output/proteincoding_corr_0.5/control_eqtl/"
pcqtl_output_dir: "output/proteincoding_corr_0.5/pcqtl/"
pc_output_dir: "output/proteincoding_corr_0.5/pcs/"
overlap_output_dir: "output/proteincoding_corr_0.5/overlap/"
annotations_output_dir: "output/proteincoding_corr_0.5/annotations/"

# for clusters
percent_corr_cutoff: .7
cutoff_type: 'value'
min_corr_cutoff: 0.4

# for cluster annotation
gencode_path: 'data/references/processed_gencode.v26.GRCh38.genes.csv'
full_abc_path: 'data/references/functional_annotations/ABC_predictions/AllPredictions.AvgHiC.ABC0.015.minus150.ForABCPaperV3.txt.gz'
abc_match_path: 'data/references/functional_annotations/ABC_predictions/ABC_matched_gtex.csv'
ctcf_match_path: 'data/references/functional_annotations/ctcf_chip/ctcf_matched_gtex.csv'
ctcf_dir: 'data/references/functional_annotations/ctcf_chip'
paralog_path: '/data/references/functional_annotations/paralogs_biomart_ensembl97.tsv.gz'
go_path: 'data/references/functional_annotations/go_biomart_ensembl97.tsv.gz'
cross_map_path: 'data/references/cross_mappability/cross_mappability_100_agg.csv'
tad_path: 'data/references/TAD_annotations/TADs_hg38/converted_HiC_IMR90_DI_10kb.txt'

