# for inputs
tissue_id_path: "data/references/selected_tissue_ids.csv"
covariates_dir: "data/processed/covariates_tami/"
expression_dir: "data/processed/normalized_expression_tami/"
chr_list_path: "data/references/chrs.csv"
genotype_stem: "data/processed/genotypes/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01"

# for outputs
filtered_expression_output_dir: "data/processed/allgened_.3_cutoff/clusters_expression/"
clusters_dir: "data/processed/allgened_.3_cutoff/clusters/"
eqtl_output_dir: "output/allgened_.3_cutoff/control_eqtl/"
pcqtl_output_dir: "output/allgened_.3_cutoff/pcqtl/"
pc_output_dir: "output/allgened_.3_cutoff/pcs/"
overlap_output_dir: "output/allgened_.3_cutoff/overlap/"
annotations_output_dir: "output/allgened_.3_cutoff/annotations/"


# for clusters
percent_corr_cutoff: .3